apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc_server
  name: grpc_server
spec:
  ports:
  - name: "30002"
    port: 5005
    targetPort: 5005
    nodePort: 30002
  selector:
    service: grpc_server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc_server
  name: grpc_server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc_server
  template:
    metadata:
      labels:
        service: grpc_server
    spec:
      containers:
      - image: hainche/grpc_server:latest
        name: grpc_server
        imagePullPolicy: Always        
