apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-person-server
  name: grpc-person-server
spec:
  ports:
  - name: "32000"
    port: 5005
    targetPort: 5005
    nodePort: 32000
  selector:
    service: grpc-person-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-person-server
  name: grpc-person-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-person-server
  template:
    metadata:
      labels:
        service: grpc-person-server
    spec:
      containers:
      - image: hainche/grpc_server:latest
        name: grpc-person-server
        imagePullPolicy: Always        
        env:
        - name: APP
          value: "person"      