apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-comsumer
  name: kafka-comsumer
spec:
  ports:
  - name: "30003"
    port: 9092
    targetPort: 9092
    nodePort: 30003
  selector:
    service: kafka-comsumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-comsumer
  name: kafka-comsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-comsumer
  template:
    metadata:
      labels:
        service: kafka-comsumer
    spec:
      containers:
      - image: hainche/kafka_consumer:latest
        name: kafka-comsumer
        imagePullPolicy: Always        
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always