apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka_comsumer
  name: kafka_comsumer
spec:
  ports:
  - name: "30003"
    port: 9092
    targetPort: 9092
    nodePort: 30003
  selector:
    service: kafka_comsumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka_comsumer
  name: kafka_comsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka_comsumer
  template:
    metadata:
      labels:
        service: kafka_comsumer
    spec:
      containers:
      - image: hainche/kafka_comsumer:latest
        name: kafka_comsumer
        imagePullPolicy: Always        
